### ISSUE TITLE
udev hwdb panic slice indexing

### ISSUE THREAD

**Issue by tuna-f1sh** [cr8t/udev#22]
Starting porting from udev to udevrs (https://github.com/tuna-f1sh/cyme/commit/b0354b65026e7342ebbbad7f2c807cf4a60ae5a6). `UdevDevice` works without issue, I found some problems with `UdevHwdb` however.

First was a panic due to end before start in `trie_string` https://github.com/cr8t/udev/compare/main...tuna-f1sh:udev:main#diff-8c30f14a46d54f1fd9c001417bf5fda08e82878fdddfef2a53df754f88267bceR26 - the end needs `+ offset` since the search starts from the offset slice but use in `hwdb_db` does not.

There was another panic in `trie_fnmatch` https://github.com/cr8t/udev/compare/main...tuna-f1sh:udev:main#diff-df9e50ce179d3f55ec8f2125b57d184f10d302c6a7ae45e4cd5757f09c671921R92. The `start` and `end` are based on the `search` string without regard for the `prefix` length? I put a guard but still don't get the right return here so not sure it's the intended use still - no longer panics though.

Did some digging but hoped you being more familiar to the codebase this might be obvious to you.

**Comment by tuna-f1sh** [comment]
Also added a test to reproduce this https://github.com/cr8t/udev/commit/2f43f007ed9cb0f6b813b4b2a1d089e0d09745f5

**Comment by cr8t** [comment]
Thanks for bringing this to my attention.

Looks like the HWDB `TrieNode` parser is borked.

[UdevHwdb::parse_nodes](https://github.com/cr8t/udev/blob/main/src/hwdb.rs#L199-L222) is meant to populate the DB entries, however it currently attempts to allocate invalid amounts of memory.

Currently, I'm storing owned lists of values in `TrieEntry` items, and this is blowing up the stack/heap for entries with large numbers of child entries.

I'm going to rewrite the parser to get iterators over the values instead of always allocating an owned list for each entry.
